spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learn-spring-boot
    username: postgres
    password: postgres
#   To eliminate warning message No operations allowed after connection closed.).
#   Possibly consider using a shorter maxLifetime value
#   keep the connection alive if idle for a long time (needed in production)
    dbcp2:
      test-on-borrow: true
      validation-query: SELECT 1
      test-while-idle: true
    hikari:
      maximum-pool-size: 30
  jpa:
    hibernate:
#     hibernate ddl auto (create, create-drop, update)
      ddl-auto: update
    generate-ddl: true
#   Show Log for each sql query
    show-sql: true

server:
  port: 8089
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
debug: false
